version: '3'

services:
  database:
    image: postgres 
    ports:
      - "8018:5432"
    environment:
      POSTGRES_DB: ShopDatabase
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: Ex@mple12345
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
